### ISSUE TITLE
Current Player wrong after changed PublicConnections

### ISSUE THREAD

**Issue by 3DPhoenix** [mordentral/AdvancedSessionsPlugin#11]
Hello, thanks for the great plugin.

I have a little problem with the default session blueprint 'GetCurrentPlayers', when changed 'PublicConnection ' with the 'Update Session'.

Default:
I create a session with 4 connections.
In  'FindSessionsAdvanced' I get the results ->GetCurrentPlayers and GetMaxPlayers: I get 1 CurrentPlayer and 4 MaxPlayers, that's works. 

If I updateSession to 3 MaxPlayers like described above I get 0 CurrentPlayer and 3 MaxPlayers
If I updateSession to 2 MaxPlayers  ... I get -1 CurrentPlayer and 2 MaxPlayers

It looks like it keeps the offset from max players of while creation the session, but do not get the real number of players.

Can you fix this?

**Comment by mordentral** [comment]
Are you testing locally or remotely after the UpdateSessions call? Because this plugin doesn't deal with any of those parts, its possible that if you are checking locally that it hasn't been updated from the server yet, which I can fix by setting right away. But if you are checking remotely on a new find command then there isn't anything I can do there, that code is all engine side.

**Comment by 3DPhoenix** [comment]
Yes, I do a later findSession-call remotely. 

I understand, that's a pity. I look for a work around. 
Thank you for your fast reply and support.
