### ISSUE TITLE
Auto Login doesn't cache UniqueNetID

### ISSUE THREAD

**Issue by LewisFarrellDev** [mordentral/AdvancedSessionsPlugin#46]
When using AutoLogin, it doesn't store the returned UniqueNetID into the Playercontroller and PlayerState, resulting in Sessions failing to create due to incorrect mapping of UniqueID.

**Comment by mordentral** [comment]
AFAIK It shouldn't be on the front end to do that, the uniquenetID setting should be all back end.

What subsystem are you using?

**Comment by LewisFarrellDev** [comment]
I'm using the EOS Subsystem.

If you look at LoginUserCallbackProxy, the OnCompleted event returns a UniqueNetID which gets cached off into the relevant places.

Now if you look at AutoLoginUserCallbackProxy, the UniqueNetID is never cached off, resulting in other systems that expect it such as "CreateSession" to fail.

**Comment by mordentral** [comment]
Yes, but its possible to login to different areas is it not? I can't automate overriding the unique net id, also AFAIK other subsystems on auto login already overwrite the net id as they call OnLoginChanged in engine code.

Everywhere else there is a unique net id being set in subsystems its done in engine code, I don't think its correct for me to be doing it manually ( i would have to filter specifically against EOS), it should be reported and fixed in engine code.
